### ISSUE TITLE
Workaround for export-books no longer necessary

### ISSUE THREAD

**Issue by C0rn3j** [BookStackApp/api-scripts#11]
https://github.com/BookStackApp/api-scripts/blob/main/php-export-all-books/export-books.php

As far as I understand, the issue was fixed in a release 3 years ago, so it shouldn't affect anyone to remove the workaround from the code.

**Comment by ssddanbrown** [comment]
Thanks @C0rn3j,
I've now removed this within the changes of 0dc645ff7bcd46e21f2806697d440e648b69bd08.
