### ISSUE TITLE
Export to DOCX

### ISSUE THREAD

**Issue by DOFfactory** [BookStackApp/api-scripts#2]
Hi, just stumbled upon these scripts. Not using Bookstack yet as I am evaluating various options at the moment but I was wondering whether it would be possible to include export into DOCX as well? I noticed couple of days ago you added import from DOCX, could we have export too? Thanks!

**Comment by ssddanbrown** [comment]
Hi @DOFfactory,
BookStack already supports "Contained" HTML exports. You could take one of these and either open directly in word, or use [pandoc](https://pandoc.org/) to explicitly convert it to a docx. That'll likely be the fastest approach.

**Comment by DOFfactory** [comment]
Hi @ssddanbrown, while I agree that these might be potential ways of achieving my request, I am thinking of deploying Bookstack for those who are not tech-savvy, to say the least. They might find it difficult to import HTML exports into Word (Word treats HTML a bit differently than DOCX files, e.g. paragraphs and line spacing). I am sure my users do not know how to use pandoc, so that is way beyond their skills. Hence the request...

**Comment by ssddanbrown** [comment]
@DOFfactory Ah, Okay, This repo is for API scripts only. If they'll find opening HTML via word, or using pandoc, difficult then I'd expect they're probably not going to be the types to run NodeJS or PHP scripts. 

A request for docx export support within the app is already existing at https://github.com/BookStackApp/BookStack/issues/1273. 

Will therefore close this off.
