### ISSUE TITLE
Integration in company erp

### ISSUE THREAD

**Issue by MadhuVuppuluri** [BookStackApp/api-scripts#8]
Our company has installed Bookstack in its server.
Now we are trying to integrate this in one of our erp just like Appsmith.
But when we tried to embed the book stack url on erp it is not opening and showing following error Refused to frame 'https://xxxxxxxx.yyy/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'". 
We found out that this particular domain is not allowing access through erp system, while it is working fine for other cases (Appsmith). We even checked the CSP setting, so that the book stack site can be plugged inside erp. But there are no issues there as well.

We also need to understand the login authentication in Bookstack from the erp screen. 
As the employees have already logged in once in the erp system so we do not want to ask them to login again to Bookstack.

**Comment by namannj46** [comment]
Thank you for integrating this into our screen. We have successfully implemented the login with Google option. However, we are currently facing a challenge in enabling login for our organization's employees. We need assistance in finding a solution that allows users with the same domain name, such as "[...@xyz.com](mailto:...@xyz.com)," to log in. Can you please help us with this?
