### ISSUE TITLE
Login through company ID for Google Login in Bookstack

### ISSUE THREAD

**Issue by MadhuVuppuluri** [BookStackApp/api-scripts#9]
Thank you for integrating this into our screen. We have successfully implemented the login with Google option. However, we are currently facing a challenge in enabling login for our organization's employees. We need assistance in finding a solution that allows users with the same domain name, such as "[...@xyz.com](mailto:...@xyz.com)," to log in. Can you please help us with this?
Currently i am able to login with google with my own id only

**Comment by ssddanbrown** [comment]
I presume #10 is a duplicate, so will close this one off since I've already replied to #10.
